name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Setup project
        run: poetry install

      - name: run test
        run: poetry run pytest -v
